<a href="https://colab.research.google.com/github/sanvi-pathare/Avocado-Ripeness-Prediction/blob/main/avocado_ripeness.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
df= pd.read_csv('/content/drive/MyDrive/avocado_ripeness_dataset.csv')
df

Mounted at /content/drive


firmness  hue  saturation  brightness color_category  sound_db  weight_g  \
0        14.5   19          40          26          black        34       175   
1        71.7   53          69          75          green        69       206   
2        88.5   60          94          46     dark green        79       220   
3        93.8  105          87          41     dark green        75       299   
4        42.5  303          58          32         purple        63       200   
..        ...  ...         ...         ...            ...       ...       ...   
245      94.1   83          80          58     dark green        72       254   
246      21.6   17          36          19          black        47       182   
247      14.0    4          40          17          black        37       188   
248      61.5   63          87          75          green        65       261   
249      17.8   27          30          36          black        40       190   

     size_cm3         ripeness  
0         261             ripe  
1         185  pre-conditioned  
2         143             hard  
3         140             hard  
4         227         breaking  
..        ...              ...  
245       134             hard  
246       240        firm-ripe  
247       274             ripe  
248       162  pre-conditioned  
249       272             ripe  

[250 rows x 9 columns]

In [ ]:
df.isnull().sum()

firmness          0
hue               0
saturation        0
brightness        0
color_category    0
sound_db          0
weight_g          0
size_cm3          0
ripeness          0
dtype: int64

In [ ]:
df.dtypes

firmness          float64
hue                 int64
saturation          int64
brightness          int64
color_category     object
sound_db            int64
weight_g            int64
size_cm3            int64
ripeness           object
dtype: object

In [ ]:
from sklearn.preprocessing import LabelEncoder
for i in ['color_category', 'ripeness']:
    df[i] = LabelEncoder().fit_transform(df[i])

In [ ]:
df.dtypes

firmness          float64
hue                 int64
saturation          int64
brightness          int64
color_category      int64
sound_db            int64
weight_g            int64
size_cm3            int64
ripeness            int64
dtype: object

In [ ]:
from sklearn.preprocessing import StandardScaler

X = df.drop(columns=['ripeness'])
y = df['ripeness']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

print("knn classifier")
print("accuracy:", accuracy_score(y_test, y_pred_knn))
print("confusion matrix:\n", confusion_matrix(y_test, y_pred_knn))
print("classification report:\n", classification_report(y_test, y_pred_knn))

knn classifier
accuracy: 0.98
confusion matrix:
 [[12  1  0  0  0]
 [ 0  9  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0  7  0]
 [ 0  0  0  0 13]]
classification report:
               precision    recall  f1-score   support

           0       1.00      0.92      0.96        13
           1       0.90      1.00      0.95         9
           2       1.00      1.00      1.00         8
           3       1.00      1.00      1.00         7
           4       1.00      1.00      1.00        13

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50

